name: Build and release Extension Catalog Image to registry

on:
  workflow_call:
    inputs:
      registry_target:
        required: true
        type: string
      registry_user:
        required: true
        type: string
    outputs:
      build-extension-catalog-job-status: 
        value: ${{ jobs.build-extension-catalog.outputs.build-status }}

jobs:
  build-and-push-extension-catalog:
    name: Build container image
    if: github.ref_type == 'tag' || (github.ref == 'refs/heads/main' && github.event_name != 'pull_request')
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      packages: write
      id-token: write
    outputs:
      build-status: ${{ job.status }}
    steps:
      
      - name: Checkout repository (normal flow)
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.0

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Build and push UI image
        run: |
          yarn publish-pkgs -cp -r ${{ inputs.registry_target }} -o ${{ inputs.registry_user }} -i ""
